/* automatically generated by generateAPI.rb */
/* START GENERATED CODE */
/********************************/
/* General Steamworks functions */
/********************************/
X(AIRSteam_Init) /* = 0 */
X(AIRSteam_RunCallbacks) /* = 1 */
X(AIRSteam_GetUserID) /* = 2 */
X(AIRSteam_GetAppID) /* = 3 */
X(AIRSteam_GetAvailableGameLanguages) /* = 4 */
X(AIRSteam_GetCurrentGameLanguage) /* = 5 */
X(AIRSteam_GetPersonaName) /* = 6 */
X(AIRSteam_RestartAppIfNecessary) /* = 7 */
/************************/
/* Stats / Achievements */
/************************/
X(AIRSteam_RequestStats) /* = 8 */
X(AIRSteam_SetAchievement) /* = 9 */
X(AIRSteam_ClearAchievement) /* = 10 */
X(AIRSteam_IsAchievement) /* = 11 */
X(AIRSteam_IndicateAchievementProgress) /* = 12 */
X(AIRSteam_GetStatInt) /* = 13 */
X(AIRSteam_GetStatFloat) /* = 14 */
X(AIRSteam_SetStatInt) /* = 15 */
X(AIRSteam_SetStatFloat) /* = 16 */
X(AIRSteam_StoreStats) /* = 17 */
X(AIRSteam_ResetAllStats) /* = 18 */
X(AIRSteam_RequestGlobalStats) /* = 19 */
X(AIRSteam_GetGlobalStatInt) /* = 20 */
X(AIRSteam_GetGlobalStatFloat) /* = 21 */
X(AIRSteam_GetGlobalStatHistoryInt) /* = 22 */
X(AIRSteam_GetGlobalStatHistoryFloat) /* = 23 */
/****************/
/* Leaderboards */
/****************/
X(AIRSteam_FindLeaderboard) /* = 24 */
X(AIRSteam_FindOrCreateLeaderboard) /* = 25 */
X(AIRSteam_FindLeaderboardResult) /* = 26 */
X(AIRSteam_GetLeaderboardName) /* = 27 */
X(AIRSteam_GetLeaderboardEntryCount) /* = 28 */
X(AIRSteam_GetLeaderboardSortMethod) /* = 29 */
X(AIRSteam_GetLeaderboardDisplayType) /* = 30 */
X(AIRSteam_UploadLeaderboardScore) /* = 31 */
X(AIRSteam_UploadLeaderboardScoreResult) /* = 32 */
X(AIRSteam_DownloadLeaderboardEntries) /* = 33 */
X(AIRSteam_DownloadLeaderboardEntriesResult) /* = 34 */
/**************************/
/* Cloud / Remote Storage */
/**************************/
X(AIRSteam_GetFileCount) /* = 35 */
X(AIRSteam_GetFileSize) /* = 36 */
X(AIRSteam_FileExists) /* = 37 */
X(AIRSteam_FileWrite) /* = 38 */
X(AIRSteam_FileRead) /* = 39 */
X(AIRSteam_FileDelete) /* = 40 */
X(AIRSteam_FileShare) /* = 41 */
X(AIRSteam_FileShareResult) /* = 42 */
X(AIRSteam_IsCloudEnabledForApp) /* = 43 */
X(AIRSteam_SetCloudEnabledForApp) /* = 44 */
X(AIRSteam_GetQuota) /* = 45 */
/******************/
/* UGC / Workshop */
/******************/
X(AIRSteam_CreateQueryUserUGCRequest) /* = 46 */
X(AIRSteam_CreateQueryAllUGCRequest) /* = 47 */
X(AIRSteam_CreateQueryUGCDetailsRequest) /* = 48 */
X(AIRSteam_SendQueryUGCRequest) /* = 49 */
X(AIRSteam_GetQueryUGCResult) /* = 50 */
X(AIRSteam_CreateItem) /* = 51 */
X(AIRSteam_CreateItemResult) /* = 52 */
X(AIRSteam_StartItemUpdate) /* = 53 */
X(AIRSteam_SetItemTitle) /* = 54 */
X(AIRSteam_SetItemDescription) /* = 55 */
X(AIRSteam_SetItemUpdateLanguage) /* = 56 */
X(AIRSteam_SetItemMetadata) /* = 57 */
X(AIRSteam_SetItemVisibility) /* = 58 */
X(AIRSteam_SetItemTags) /* = 59 */
X(AIRSteam_SetItemContent) /* = 60 */
X(AIRSteam_SetItemPreview) /* = 61 */
X(AIRSteam_AddItemKeyValueTag) /* = 62 */
X(AIRSteam_RemoveItemKeyValueTags) /* = 63 */
X(AIRSteam_SubmitItemUpdate) /* = 64 */
X(AIRSteam_SubscribeItem) /* = 65 */
X(AIRSteam_UnsubscribeItem) /* = 66 */
X(AIRSteam_GetSubscribedItems) /* = 67 */
X(AIRSteam_GetItemState) /* = 68 */
X(AIRSteam_GetItemInstallInfo) /* = 69 */
X(AIRSteam_GetItemDownloadInfo) /* = 70 */
X(AIRSteam_DownloadItem) /* = 71 */
/***********/
/* Friends */
/***********/
X(AIRSteam_GetFriendCount) /* = 72 */
X(AIRSteam_GetFriendByIndex) /* = 73 */
X(AIRSteam_GetFriendPersonaName) /* = 74 */
/******************************/
/* Authentication & Ownership */
/******************************/
X(AIRSteam_GetAuthSessionTicket) /* = 75 */
X(AIRSteam_GetAuthSessionTicketResult) /* = 76 */
X(AIRSteam_BeginAuthSession) /* = 77 */
X(AIRSteam_EndAuthSession) /* = 78 */
X(AIRSteam_CancelAuthTicket) /* = 79 */
X(AIRSteam_UserHasLicenseForApp) /* = 80 */
/***********/
/* Overlay */
/***********/
X(AIRSteam_ActivateGameOverlay) /* = 81 */
X(AIRSteam_ActivateGameOverlayToUser) /* = 82 */
X(AIRSteam_ActivateGameOverlayToWebPage) /* = 83 */
X(AIRSteam_ActivateGameOverlayToStore) /* = 84 */
X(AIRSteam_ActivateGameOverlayInviteDialog) /* = 85 */
X(AIRSteam_IsOverlayEnabled) /* = 86 */
X(AIRSteam_SetOverlayNotificationPosition) /* = 87 */
/***********************/
/* DLC / subscriptions */
/***********************/
X(AIRSteam_IsSubscribedApp) /* = 88 */
X(AIRSteam_IsDLCInstalled) /* = 89 */
X(AIRSteam_GetDLCCount) /* = 90 */
X(AIRSteam_InstallDLC) /* = 91 */
X(AIRSteam_UninstallDLC) /* = 92 */
X(AIRSteam_DLCInstalledResult) /* = 93 */
/********************/
/* Microtransaction */
/********************/
X(AIRSteam_MicroTxnResult) /* = 94 */
/**********************************/
/* Other non-Steamworks functions */
/**********************************/
X(AIRSteam_GetEnv) /* = 95 */
X(AIRSteam_SetEnv) /* = 96 */
/* END GENERATED CODE */
